package com.redhat.loja_online;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cliente implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Cliente() {
    }




}