package com.redhat.loja_online;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Produto implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Produto() {
    }




}